INSERT INTO travel_act_avg_like VALUES('Culinary Tourism', 4.58, 4.56);
INSERT INTO travel_act_avg_like VALUES('Shopping', 4.62, 4.63);
INSERT INTO travel_act_avg_like VALUES('Enjoying Natural Scenery', 4.69, 4.72);
INSERT INTO travel_act_avg_like VALUES('Visit to Palaces/Historical Sites', 4.74, 4.78);
INSERT INTO travel_act_avg_like VALUES('Experience Traditional Culture', 4.77, 4.8);
INSERT INTO travel_act_avg_like VALUES('Visit to Museums and Exhibitions', 4.75, 4.78);
INSERT INTO travel_act_avg_like VALUES('Visit to K-POP/Hallyu Star-related Performances', 4.7, 4.73);
INSERT INTO travel_act_avg_like VALUES('Visit to Drama/Movie Shooting Locations', 4.74, 4.83);
INSERT INTO travel_act_avg_like VALUES('Watching Performances such as Theater, Musicals, Ballet, and Participating in Local Festivals', 4.71, 4.76);
INSERT INTO travel_act_avg_like VALUES('Participating in Local Festivals', 4.68, 4.76);
INSERT INTO travel_act_avg_like VALUES('Entertainment/Recreation', 4.72, 4.77);
INSERT INTO travel_act_avg_like VALUES('Beauty/Medical Tourism', 4.69, 4.72);
INSERT INTO travel_act_avg_like VALUES('Sports/Recreation Watching and Participation Business Activities', 4.71, 4.75);
INSERT INTO travel_act_avg_like VALUES('Business Transactions', 4.46, 4.47);
INSERT INTO travel_act_avg_like VALUES('Training/Education/Research', 4.64, 4.63);
INSERT INTO travel_act_avg_like VALUES('Inspection (Industrial Facilities, etc.)', 4.32, 4.41);
