INSERT INTO travel_act_avg_like VALUES('식도락 관광', 4.58, 4.56);
INSERT INTO travel_act_avg_like VALUES('쇼핑', 4.62, 4.63);
INSERT INTO travel_act_avg_like VALUES('자연경관 감상', 4.69, 4.72);
INSERT INTO travel_act_avg_like VALUES('고궁/역사 유적지 방문', 4.74, 4.78);
INSERT INTO travel_act_avg_like VALUES('전통문화체험', 4.77, 4.8);
INSERT INTO travel_act_avg_like VALUES('박물관, 전시관 관람', 4.75, 4.78);
INSERT INTO travel_act_avg_like VALUES('K-POP/한류스타 관련 공연장 방문', 4.7, 4.73);
INSERT INTO travel_act_avg_like VALUES('드라마/영화 촬영지 방문', 4.74, 4.83);
INSERT INTO travel_act_avg_like VALUES('연극, 뮤지컬, 발레 등 공연 관람 및 지역 축제 참여', 4.71, 4.76);
INSERT INTO travel_act_avg_like VALUES('지역 축제 참여', 4.68, 4.76);
INSERT INTO travel_act_avg_like VALUES('유흥/오락', 4.72, 4.77);
INSERT INTO travel_act_avg_like VALUES('뷰티/의료관광', 4.69, 4.72);
INSERT INTO travel_act_avg_like VALUES('스포츠/레포츠 관람 및 참가 비즈니스 활동', 4.71, 4.75);
INSERT INTO travel_act_avg_like VALUES('업무수행', 4.46, 4.47);
INSERT INTO travel_act_avg_like VALUES('연수/교육/연구', 4.64, 4.63);
INSERT INTO travel_act_avg_like VALUES('시찰 (산업시설 등)', 4.32, 4.41);
