INSERT INTO travel_like_avg_location VALUES('서울', 4.66, 4.64);
INSERT INTO travel_like_avg_location VALUES('경기도', 4.58, 4.57);
INSERT INTO travel_like_avg_location VALUES('인천', 4.71, 4.66);
INSERT INTO travel_like_avg_location VALUES('강원도', 4.75, 4.74);
INSERT INTO travel_like_avg_location VALUES('충청도', 4.49, 4.49);
INSERT INTO travel_like_avg_location VALUES('경상도', 4.68, 4.64);
INSERT INTO travel_like_avg_location VALUES('전라도', 4.66, 4.64);
INSERT INTO travel_like_avg_location VALUES('제주', 4.77, 4.73);


INSERT INTO travel_revisit VALUES('여성', 15, '식도락 관광', 4.55);
INSERT INTO travel_revisit VALUES('여성', 15, '쇼핑', 4.59);
INSERT INTO travel_revisit VALUES('여성', 15, '자연경관 감상', 4.6);
INSERT INTO travel_revisit VALUES('여성', 15, '고궁/역사 유적지 방문', 4.3);
INSERT INTO travel_revisit VALUES('여성', 15, '전통문화체험', 0);
INSERT INTO travel_revisit VALUES('여성', 15, '박물관, 전시관 관람', 0);
INSERT INTO travel_revisit VALUES('여성', 15, 'K-POP/한류스타 관련 공연장 방문', 0);
INSERT INTO travel_revisit VALUES('여성', 15, '드라마/영화 촬영지 방문', 0);
INSERT INTO travel_revisit VALUES('여성', 15, '연극, 뮤지컬, 발레 등 공연 관람 및 지역 축제 참여', 0);
INSERT INTO travel_revisit VALUES('여성', 15, '지역 축제 참여', 5);
INSERT INTO travel_revisit VALUES('여성', 15, '유흥/오락', 4);
INSERT INTO travel_revisit VALUES('여성', 15, '뷰티/의료관광', 5);
INSERT INTO travel_revisit VALUES('여성', 15, '스포츠/레포츠 관람 및 참가 비즈니스 활동', 0);
INSERT INTO travel_revisit VALUES('여성', 15, '업무수행', 4.53);
INSERT INTO travel_revisit VALUES('여성', 15, '연수/교육/연구', 4.83);
INSERT INTO travel_revisit VALUES('여성', 15, '시찰 (산업시설 등)', 0);
INSERT INTO travel_revisit VALUES('여성', 21, '식도락 관광', 4.48);
INSERT INTO travel_revisit VALUES('여성', 21, '쇼핑', 4.48);
INSERT INTO travel_revisit VALUES('여성', 21, '자연경관 감상', 4.35);
INSERT INTO travel_revisit VALUES('여성', 21, '고궁/역사 유적지 방문', 4.71);
INSERT INTO travel_revisit VALUES('여성', 21, '전통문화체험', 5);
INSERT INTO travel_revisit VALUES('여성', 21, '박물관, 전시관 관람', 4.33);
INSERT INTO travel_revisit VALUES('여성', 21, 'K-POP/한류스타 관련 공연장 방문', 5);
INSERT INTO travel_revisit VALUES('여성', 21, '드라마/영화 촬영지 방문', 0);
INSERT INTO travel_revisit VALUES('여성', 21, '연극, 뮤지컬, 발레 등 공연 관람 및 지역 축제 참여', 5);
INSERT INTO travel_revisit VALUES('여성', 21, '지역 축제 참여', 0);
INSERT INTO travel_revisit VALUES('여성', 21, '유흥/오락', 0);
INSERT INTO travel_revisit VALUES('여성', 21, '뷰티/의료관광', 4.4);
INSERT INTO travel_revisit VALUES('여성', 21, '스포츠/레포츠 관람 및 참가 비즈니스 활동', 5);
INSERT INTO travel_revisit VALUES('여성', 21, '업무수행', 4.52);
INSERT INTO travel_revisit VALUES('여성', 21, '연수/교육/연구', 4.55);
INSERT INTO travel_revisit VALUES('여성', 21, '시찰 (산업시설 등)', 0);
INSERT INTO travel_revisit VALUES('여성', 31, '식도락 관광', 4.54);
INSERT INTO travel_revisit VALUES('여성', 31, '쇼핑', 4.58);
INSERT INTO travel_revisit VALUES('여성', 31, '자연경관 감상', 4.29);
INSERT INTO travel_revisit VALUES('여성', 31, '고궁/역사 유적지 방문', 4.67);
INSERT INTO travel_revisit VALUES('여성', 31, '전통문화체험', 5);
INSERT INTO travel_revisit VALUES('여성', 31, '박물관, 전시관 관람', 4.5);
INSERT INTO travel_revisit VALUES('여성', 31, 'K-POP/한류스타 관련 공연장 방문', 5);
INSERT INTO travel_revisit VALUES('여성', 31, '드라마/영화 촬영지 방문', 0);
INSERT INTO travel_revisit VALUES('여성', 31, '연극, 뮤지컬, 발레 등 공연 관람 및 지역 축제 참여', 0);
INSERT INTO travel_revisit VALUES('여성', 31, '지역 축제 참여', 0);
INSERT INTO travel_revisit VALUES('여성', 31, '유흥/오락', 0);
INSERT INTO travel_revisit VALUES('여성', 31, '뷰티/의료관광', 0);
INSERT INTO travel_revisit VALUES('여성', 31, '스포츠/레포츠 관람 및 참가 비즈니스 활동', 5);
INSERT INTO travel_revisit VALUES('여성', 31, '업무수행', 4.51);
INSERT INTO travel_revisit VALUES('여성', 31, '연수/교육/연구', 4);
INSERT INTO travel_revisit VALUES('여성', 31, '시찰 (산업시설 등)', 5);
INSERT INTO travel_revisit VALUES('여성', 41, '식도락 관광', 4.6);
INSERT INTO travel_revisit VALUES('여성', 41, '쇼핑', 4.53);
INSERT INTO travel_revisit VALUES('여성', 41, '자연경관 감상', 4.75);
INSERT INTO travel_revisit VALUES('여성', 41, '고궁/역사 유적지 방문', 4.86);
INSERT INTO travel_revisit VALUES('여성', 41, '전통문화체험', 0);
INSERT INTO travel_revisit VALUES('여성', 41, '박물관, 전시관 관람', 0);
INSERT INTO travel_revisit VALUES('여성', 41, 'K-POP/한류스타 관련 공연장 방문', 0);
INSERT INTO travel_revisit VALUES('여성', 41, '드라마/영화 촬영지 방문', 0);
INSERT INTO travel_revisit VALUES('여성', 41, '연극, 뮤지컬, 발레 등 공연 관람 및 지역 축제 참여', 5);
INSERT INTO travel_revisit VALUES('여성', 41, '지역 축제 참여', 0);
INSERT INTO travel_revisit VALUES('여성', 41, '유흥/오락', 0);
INSERT INTO travel_revisit VALUES('여성', 41, '뷰티/의료관광', 0);
INSERT INTO travel_revisit VALUES('여성', 41, '스포츠/레포츠 관람 및 참가 비즈니스 활동', 0);
INSERT INTO travel_revisit VALUES('여성', 41, '업무수행', 4.44);
INSERT INTO travel_revisit VALUES('여성', 41, '연수/교육/연구', 4.67);
INSERT INTO travel_revisit VALUES('여성', 41, '시찰 (산업시설 등)', 0);
INSERT INTO travel_revisit VALUES('여성', 51, '식도락 관광', 4.51);
INSERT INTO travel_revisit VALUES('여성', 51, '쇼핑', 4.57);
INSERT INTO travel_revisit VALUES('여성', 51, '자연경관 감상', 4.67);
INSERT INTO travel_revisit VALUES('여성', 51, '고궁/역사 유적지 방문', 5);
INSERT INTO travel_revisit VALUES('여성', 51, '전통문화체험', 0);
INSERT INTO travel_revisit VALUES('여성', 51, '박물관, 전시관 관람', 0);
INSERT INTO travel_revisit VALUES('여성', 51, 'K-POP/한류스타 관련 공연장 방문', 0);
INSERT INTO travel_revisit VALUES('여성', 51, '드라마/영화 촬영지 방문', 0);
INSERT INTO travel_revisit VALUES('여성', 51, '연극, 뮤지컬, 발레 등 공연 관람 및 지역 축제 참여', 0);
INSERT INTO travel_revisit VALUES('여성', 51, '지역 축제 참여', 0);
INSERT INTO travel_revisit VALUES('여성', 51, '유흥/오락', 0);
INSERT INTO travel_revisit VALUES('여성', 51, '뷰티/의료관광', 0);
INSERT INTO travel_revisit VALUES('여성', 51, '스포츠/레포츠 관람 및 참가 비즈니스 활동', 0);
INSERT INTO travel_revisit VALUES('여성', 51, '업무수행', 4.58);
INSERT INTO travel_revisit VALUES('여성', 51, '연수/교육/연구', 5);
INSERT INTO travel_revisit VALUES('여성', 51, '시찰 (산업시설 등)', 0);
INSERT INTO travel_revisit VALUES('여성', 61, '식도락 관광', 4.21);
INSERT INTO travel_revisit VALUES('여성', 61, '쇼핑', 4.77);
INSERT INTO travel_revisit VALUES('여성', 61, '자연경관 감상', 4.5);
INSERT INTO travel_revisit VALUES('여성', 61, '고궁/역사 유적지 방문', 0);
INSERT INTO travel_revisit VALUES('여성', 61, '전통문화체험', 0);
INSERT INTO travel_revisit VALUES('여성', 61, '박물관, 전시관 관람', 0);
INSERT INTO travel_revisit VALUES('여성', 61, 'K-POP/한류스타 관련 공연장 방문', 0);
INSERT INTO travel_revisit VALUES('여성', 61, '드라마/영화 촬영지 방문', 0);
INSERT INTO travel_revisit VALUES('여성', 61, '연극, 뮤지컬, 발레 등 공연 관람 및 지역 축제 참여', 0);
INSERT INTO travel_revisit VALUES('여성', 61, '지역 축제 참여', 0);
INSERT INTO travel_revisit VALUES('여성', 61, '유흥/오락', 0);
INSERT INTO travel_revisit VALUES('여성', 61, '뷰티/의료관광', 0);
INSERT INTO travel_revisit VALUES('여성', 61, '스포츠/레포츠 관람 및 참가 비즈니스 활동', 5);
INSERT INTO travel_revisit VALUES('여성', 61, '업무수행', 4.75);
INSERT INTO travel_revisit VALUES('여성', 61, '연수/교육/연구', 4);
INSERT INTO travel_revisit VALUES('여성', 61, '시찰 (산업시설 등)', 0);
INSERT INTO travel_revisit VALUES('남성', 15, '식도락 관광', 4.46);
INSERT INTO travel_revisit VALUES('남성', 15, '쇼핑', 4.46);
INSERT INTO travel_revisit VALUES('남성', 15, '자연경관 감상', 4.75);
INSERT INTO travel_revisit VALUES('남성', 15, '고궁/역사 유적지 방문', 1);
INSERT INTO travel_revisit VALUES('남성', 15, '전통문화체험', 0);
INSERT INTO travel_revisit VALUES('남성', 15, '박물관, 전시관 관람', 0);
INSERT INTO travel_revisit VALUES('남성', 15, 'K-POP/한류스타 관련 공연장 방문', 0);
INSERT INTO travel_revisit VALUES('남성', 15, '드라마/영화 촬영지 방문', 4);
INSERT INTO travel_revisit VALUES('남성', 15, '연극, 뮤지컬, 발레 등 공연 관람 및 지역 축제 참여', 0);
INSERT INTO travel_revisit VALUES('남성', 15, '지역 축제 참여', 0);
INSERT INTO travel_revisit VALUES('남성', 15, '유흥/오락', 0);
INSERT INTO travel_revisit VALUES('남성', 15, '뷰티/의료관광', 0);
INSERT INTO travel_revisit VALUES('남성', 15, '스포츠/레포츠 관람 및 참가 비즈니스 활동', 0);
INSERT INTO travel_revisit VALUES('남성', 15, '업무수행', 4.71);
INSERT INTO travel_revisit VALUES('남성', 15, '연수/교육/연구', 4.2);
INSERT INTO travel_revisit VALUES('남성', 15, '시찰 (산업시설 등)', 0);
INSERT INTO travel_revisit VALUES('남성', 21, '식도락 관광', 4.34);
INSERT INTO travel_revisit VALUES('남성', 21, '쇼핑', 4.26);
INSERT INTO travel_revisit VALUES('남성', 21, '자연경관 감상', 4.04);
INSERT INTO travel_revisit VALUES('남성', 21, '고궁/역사 유적지 방문', 4.47);
INSERT INTO travel_revisit VALUES('남성', 21, '전통문화체험', 4.75);
INSERT INTO travel_revisit VALUES('남성', 21, '박물관, 전시관 관람', 4.4);
INSERT INTO travel_revisit VALUES('남성', 21, 'K-POP/한류스타 관련 공연장 방문', 0);
INSERT INTO travel_revisit VALUES('남성', 21, '드라마/영화 촬영지 방문', 0);
INSERT INTO travel_revisit VALUES('남성', 21, '연극, 뮤지컬, 발레 등 공연 관람 및 지역 축제 참여', 0);
INSERT INTO travel_revisit VALUES('남성', 21, '지역 축제 참여', 0);
INSERT INTO travel_revisit VALUES('남성', 21, '유흥/오락', 3.67);
INSERT INTO travel_revisit VALUES('남성', 21, '뷰티/의료관광', 4.75);
INSERT INTO travel_revisit VALUES('남성', 21, '스포츠/레포츠 관람 및 참가 비즈니스 활동', 4);
INSERT INTO travel_revisit VALUES('남성', 21, '업무수행', 4.41);
INSERT INTO travel_revisit VALUES('남성', 21, '연수/교육/연구', 4.21);
INSERT INTO travel_revisit VALUES('남성', 21, '시찰 (산업시설 등)', 1.5);
INSERT INTO travel_revisit VALUES('남성', 31, '식도락 관광', 4.33);
INSERT INTO travel_revisit VALUES('남성', 31, '쇼핑', 4.37);
INSERT INTO travel_revisit VALUES('남성', 31, '자연경관 감상', 4.38);
INSERT INTO travel_revisit VALUES('남성', 31, '고궁/역사 유적지 방문', 4.06);
INSERT INTO travel_revisit VALUES('남성', 31, '전통문화체험', 4);
INSERT INTO travel_revisit VALUES('남성', 31, '박물관, 전시관 관람', 3.67);
INSERT INTO travel_revisit VALUES('남성', 31, 'K-POP/한류스타 관련 공연장 방문', 0);
INSERT INTO travel_revisit VALUES('남성', 31, '드라마/영화 촬영지 방문', 4);
INSERT INTO travel_revisit VALUES('남성', 31, '연극, 뮤지컬, 발레 등 공연 관람 및 지역 축제 참여', 0);
INSERT INTO travel_revisit VALUES('남성', 31, '지역 축제 참여', 0);
INSERT INTO travel_revisit VALUES('남성', 31, '유흥/오락', 4);
INSERT INTO travel_revisit VALUES('남성', 31, '뷰티/의료관광', 0);
INSERT INTO travel_revisit VALUES('남성', 31, '스포츠/레포츠 관람 및 참가 비즈니스 활동', 5);
INSERT INTO travel_revisit VALUES('남성', 31, '업무수행', 4.47);
INSERT INTO travel_revisit VALUES('남성', 31, '연수/교육/연구', 4.38);
INSERT INTO travel_revisit VALUES('남성', 31, '시찰 (산업시설 등)', 5);
INSERT INTO travel_revisit VALUES('남성', 41, '식도락 관광', 4.47);
INSERT INTO travel_revisit VALUES('남성', 41, '쇼핑', 4.48);
INSERT INTO travel_revisit VALUES('남성', 41, '자연경관 감상', 4.28);
INSERT INTO travel_revisit VALUES('남성', 41, '고궁/역사 유적지 방문', 4.5);
INSERT INTO travel_revisit VALUES('남성', 41, '전통문화체험', 4);
INSERT INTO travel_revisit VALUES('남성', 41, '박물관, 전시관 관람', 4);
INSERT INTO travel_revisit VALUES('남성', 41, 'K-POP/한류스타 관련 공연장 방문', 0);
INSERT INTO travel_revisit VALUES('남성', 41, '드라마/영화 촬영지 방문', 4);
INSERT INTO travel_revisit VALUES('남성', 41, '연극, 뮤지컬, 발레 등 공연 관람 및 지역 축제 참여', 0);
INSERT INTO travel_revisit VALUES('남성', 41, '지역 축제 참여', 0);
INSERT INTO travel_revisit VALUES('남성', 41, '유흥/오락', 0);
INSERT INTO travel_revisit VALUES('남성', 41, '뷰티/의료관광', 4.5);
INSERT INTO travel_revisit VALUES('남성', 41, '스포츠/레포츠 관람 및 참가 비즈니스 활동', 5);
INSERT INTO travel_revisit VALUES('남성', 41, '업무수행', 4.4);
INSERT INTO travel_revisit VALUES('남성', 41, '연수/교육/연구', 4.27);
INSERT INTO travel_revisit VALUES('남성', 41, '시찰 (산업시설 등)', 5);
INSERT INTO travel_revisit VALUES('남성', 51, '식도락 관광', 4.51);
INSERT INTO travel_revisit VALUES('남성', 51, '쇼핑', 4.51);
INSERT INTO travel_revisit VALUES('남성', 51, '자연경관 감상', 4.43);
INSERT INTO travel_revisit VALUES('남성', 51, '고궁/역사 유적지 방문', 4.67);
INSERT INTO travel_revisit VALUES('남성', 51, '전통문화체험', 5);
INSERT INTO travel_revisit VALUES('남성', 51, '박물관, 전시관 관람', 4);
INSERT INTO travel_revisit VALUES('남성', 51, 'K-POP/한류스타 관련 공연장 방문', 0);
INSERT INTO travel_revisit VALUES('남성', 51, '드라마/영화 촬영지 방문', 0);
INSERT INTO travel_revisit VALUES('남성', 51, '연극, 뮤지컬, 발레 등 공연 관람 및 지역 축제 참여', 0);
INSERT INTO travel_revisit VALUES('남성', 51, '지역 축제 참여', 0);
INSERT INTO travel_revisit VALUES('남성', 51, '유흥/오락', 5);
INSERT INTO travel_revisit VALUES('남성', 51, '뷰티/의료관광', 5);
INSERT INTO travel_revisit VALUES('남성', 51, '스포츠/레포츠 관람 및 참가 비즈니스 활동', 5);
INSERT INTO travel_revisit VALUES('남성', 51, '업무수행', 4.54);
INSERT INTO travel_revisit VALUES('남성', 51, '연수/교육/연구', 4);
INSERT INTO travel_revisit VALUES('남성', 51, '시찰 (산업시설 등)', 0);
INSERT INTO travel_revisit VALUES('남성', 61, '식도락 관광', 4.58);
INSERT INTO travel_revisit VALUES('남성', 61, '쇼핑', 4.69);
INSERT INTO travel_revisit VALUES('남성', 61, '자연경관 감상', 4.4);
INSERT INTO travel_revisit VALUES('남성', 61, '고궁/역사 유적지 방문', 0);
INSERT INTO travel_revisit VALUES('남성', 61, '전통문화체험', 0);
INSERT INTO travel_revisit VALUES('남성', 61, '박물관, 전시관 관람', 0);
INSERT INTO travel_revisit VALUES('남성', 61, 'K-POP/한류스타 관련 공연장 방문', 0);
INSERT INTO travel_revisit VALUES('남성', 61, '드라마/영화 촬영지 방문', 0);
INSERT INTO travel_revisit VALUES('남성', 61, '연극, 뮤지컬, 발레 등 공연 관람 및 지역 축제 참여', 0);
INSERT INTO travel_revisit VALUES('남성', 61, '지역 축제 참여', 0);
INSERT INTO travel_revisit VALUES('남성', 61, '유흥/오락', 0);
INSERT INTO travel_revisit VALUES('남성', 61, '뷰티/의료관광', 0);
INSERT INTO travel_revisit VALUES('남성', 61, '스포츠/레포츠 관람 및 참가 비즈니스 활동', 0);
INSERT INTO travel_revisit VALUES('남성', 61, '업무수행', 4.59);
INSERT INTO travel_revisit VALUES('남성', 61, '연수/교육/연구', 0);
INSERT INTO travel_revisit VALUES('남성', 61, '시찰 (산업시설 등)', 0);
