INSERT INTO travel_like_avg_location VALUES('서울', 4.66, 4.64);
INSERT INTO travel_like_avg_location VALUES('경기도', 4.58, 4.57);
INSERT INTO travel_like_avg_location VALUES('인천', 4.71, 4.66);
INSERT INTO travel_like_avg_location VALUES('강원도', 4.75, 4.74);
INSERT INTO travel_like_avg_location VALUES('충청도', 4.49, 4.49);
INSERT INTO travel_like_avg_location VALUES('경상도', 4.68, 4.64);
INSERT INTO travel_like_avg_location VALUES('전라도', 4.66, 4.64);
INSERT INTO travel_like_avg_location VALUES('제주', 4.77, 4.73);


INSERT INTO travel_revisit VALUES('여성', 15, '식도락 관광', 4.55);
INSERT INTO travel_revisit VALUES('여성', 15, '쇼핑', 4.59);
INSERT INTO travel_revisit VALUES('여성', 15, '자연경관 감상', 4.6);
INSERT INTO travel_revisit VALUES('여성', 15, '고궁/역사 유적지 방문', 4.3);
INSERT INTO travel_revisit VALUES('여성', 15, '전통문화체험', 0);
INSERT INTO travel_revisit VALUES('여성', 15, '박물관, 전시관 관람', 0);
INSERT INTO travel_revisit VALUES('여성', 15, 'K-POP/한류스타 관련 공연장 방문', 0);
INSERT INTO travel_revisit VALUES('여성', 15, '드라마/영화 촬영지 방문', 0);
INSERT INTO travel_revisit VALUES('여성', 15, '연극, 뮤지컬, 발레 등 공연 관람 및 지역 축제 참여', 0);
INSERT INTO travel_revisit VALUES('여성', 15, '지역 축제 참여', 5);
INSERT INTO travel_revisit VALUES('여성', 15, '유흥/오락', 4);
INSERT INTO travel_revisit VALUES('여성', 15, '뷰티/의료관광', 5);
INSERT INTO travel_revisit VALUES('여성', 15, '스포츠/레포츠 관람 및 참가 비즈니스 활동', 0);
INSERT INTO travel_revisit VALUES('여성', 15, '업무수행', 4.53);
INSERT INTO travel_revisit VALUES('여성', 15, '연수/교육/연구', 4.83);
INSERT INTO travel_revisit VALUES('여성', 15, '시찰 (산업시설 등)', 0);
INSERT INTO travel_revisit VALUES('여성', 21, '식도락 관광', 4.48);
INSERT INTO travel_revisit VALUES('여성', 21, '쇼핑', 4.48);
INSERT INTO travel_revisit VALUES('여성', 21, '자연경관 감상', 4.35);
INSERT INTO travel_revisit VALUES('여성', 21, '고궁/역사 유적지 방문', 4.71);
INSERT INTO travel_revisit VALUES('여성', 21, '전통문화체험', 5);
INSERT INTO travel_revisit VALUES('여성', 21, '박물관, 전시관 관람', 4.33);
INSERT INTO travel_revisit VALUES('여성', 21, 'K-POP/한류스타 관련 공연장 방문', 5);
INSERT INTO travel_revisit VALUES('여성', 21, '드라마/영화 촬영지 방문', 0);
INSERT INTO travel_revisit VALUES('여성', 21, '연극, 뮤지컬, 발레 등 공연 관람 및 지역 축제 참여', 5);
INSERT INTO travel_revisit VALUES('여성', 21, '지역 축제 참여', 0);
INSERT INTO travel_revisit VALUES('여성', 21, '유흥/오락', 0);
INSERT INTO travel_revisit VALUES('여성', 21, '뷰티/의료관광', 4.4);
INSERT INTO travel_revisit VALUES('여성', 21, '스포츠/레포츠 관람 및 참가 비즈니스 활동', 5);
INSERT INTO travel_revisit VALUES('여성', 21, '업무수행', 4.52);
INSERT INTO travel_revisit VALUES('여성', 21, '연수/교육/연구', 4.55);
INSERT INTO travel_revisit VALUES('여성', 21, '시찰 (산업시설 등)', 0);
INSERT INTO travel_revisit VALUES('여성', 31, '식도락 관광', 4.54);
INSERT INTO travel_revisit VALUES('여성', 31, '쇼핑', 4.58);
INSERT INTO travel_revisit VALUES('여성', 31, '자연경관 감상', 4.29);
INSERT INTO travel_revisit VALUES('여성', 31, '고궁/역사 유적지 방문', 4.67);
INSERT INTO travel_revisit VALUES('여성', 31, '전통문화체험', 5);
INSERT INTO travel_revisit VALUES('여성', 31, '박물관, 전시관 관람', 4.5);
INSERT INTO travel_revisit VALUES('여성', 31, 'K-POP/한류스타 관련 공연장 방문', 5);
INSERT INTO travel_revisit VALUES('여성', 31, '드라마/영화 촬영지 방문', 0);
INSERT INTO travel_revisit VALUES('여성', 31, '연극, 뮤지컬, 발레 등 공연 관람 및 지역 축제 참여', 0);
INSERT INTO travel_revisit VALUES('여성', 31, '지역 축제 참여', 0);
INSERT INTO travel_revisit VALUES('여성', 31, '유흥/오락', 0);
INSERT INTO travel_revisit VALUES('여성', 31, '뷰티/의료관광', 0);
INSERT INTO travel_revisit VALUES('여성', 31, '스포츠/레포츠 관람 및 참가 비즈니스 활동', 5);
INSERT INTO travel_revisit VALUES('여성', 31, '업무수행', 4.51);
INSERT INTO travel_revisit VALUES('여성', 31, '연수/교육/연구', 4);
INSERT INTO travel_revisit VALUES('여성', 31, '시찰 (산업시설 등)', 5);
INSERT INTO travel_revisit VALUES('여성', 41, '식도락 관광', 4.6);
INSERT INTO travel_revisit VALUES('여성', 41, '쇼핑', 4.53);
INSERT INTO travel_revisit VALUES('여성', 41, '자연경관 감상', 4.75);
INSERT INTO travel_revisit VALUES('여성', 41, '고궁/역사 유적지 방문', 4.86);
INSERT INTO travel_revisit VALUES('여성', 41, '전통문화체험', 0);
INSERT INTO travel_revisit VALUES('여성', 41, '박물관, 전시관 관람', 0);
INSERT INTO travel_revisit VALUES('여성', 41, 'K-POP/한류스타 관련 공연장 방문', 0);
INSERT INTO travel_revisit VALUES('여성', 41, '드라마/영화 촬영지 방문', 0);
INSERT INTO travel_revisit VALUES('여성', 41, '연극, 뮤지컬, 발레 등 공연 관람 및 지역 축제 참여', 5);
INSERT INTO travel_revisit VALUES('여성', 41, '지역 축제 참여', 0);
INSERT INTO travel_revisit VALUES('여성', 41, '유흥/오락', 0);
INSERT INTO travel_revisit VALUES('여성', 41, '뷰티/의료관광', 0);
INSERT INTO travel_revisit VALUES('여성', 41, '스포츠/레포츠 관람 및 참가 비즈니스 활동', 0);
INSERT INTO travel_revisit VALUES('여성', 41, '업무수행', 4.44);
INSERT INTO travel_revisit VALUES('여성', 41, '연수/교육/연구', 4.67);
INSERT INTO travel_revisit VALUES('여성', 41, '시찰 (산업시설 등)', 0);
INSERT INTO travel_revisit VALUES('여성', 51, '식도락 관광', 4.51);
INSERT INTO travel_revisit VALUES('여성', 51, '쇼핑', 4.57);
INSERT INTO travel_revisit VALUES('여성', 51, '자연경관 감상', 4.67);
INSERT INTO travel_revisit VALUES('여성', 51, '고궁/역사 유적지 방문', 5);
INSERT INTO travel_revisit VALUES('여성', 51, '전통문화체험', 0);
INSERT INTO travel_revisit VALUES('여성', 51, '박물관, 전시관 관람', 0);
INSERT INTO travel_revisit VALUES('여성', 51, 'K-POP/한류스타 관련 공연장 방문', 0);
INSERT INTO travel_revisit VALUES('여성', 51, '드라마/영화 촬영지 방문', 0);
INSERT INTO travel_revisit VALUES('여성', 51, '연극, 뮤지컬, 발레 등 공연 관람 및 지역 축제 참여', 0);
INSERT INTO travel_revisit VALUES('여성', 51, '지역 축제 참여', 0);
INSERT INTO travel_revisit VALUES('여성', 51, '유흥/오락', 0);
INSERT INTO travel_revisit VALUES('여성', 51, '뷰티/의료관광', 0);
INSERT INTO travel_revisit VALUES('여성', 51, '스포츠/레포츠 관람 및 참가 비즈니스 활동', 0);
INSERT INTO travel_revisit VALUES('여성', 51, '업무수행', 4.58);
INSERT INTO travel_revisit VALUES('여성', 51, '연수/교육/연구', 5);
INSERT INTO travel_revisit VALUES('여성', 51, '시찰 (산업시설 등)', 0);
INSERT INTO travel_revisit VALUES('여성', 61, '식도락 관광', 4.21);
INSERT INTO travel_revisit VALUES('여성', 61, '쇼핑', 4.77);
INSERT INTO travel_revisit VALUES('여성', 61, '자연경관 감상', 4.5);
INSERT INTO travel_revisit VALUES('여성', 61, '고궁/역사 유적지 방문', 0);
INSERT INTO travel_revisit VALUES('여성', 61, '전통문화체험', 0);
INSERT INTO travel_revisit VALUES('여성', 61, '박물관, 전시관 관람', 0);
INSERT INTO travel_revisit VALUES('여성', 61, 'K-POP/한류스타 관련 공연장 방문', 0);
INSERT INTO travel_revisit VALUES('여성', 61, '드라마/영화 촬영지 방문', 0);
INSERT INTO travel_revisit VALUES('여성', 61, '연극, 뮤지컬, 발레 등 공연 관람 및 지역 축제 참여', 0);
INSERT INTO travel_revisit VALUES('여성', 61, '지역 축제 참여', 0);
INSERT INTO travel_revisit VALUES('여성', 61, '유흥/오락', 0);
INSERT INTO travel_revisit VALUES('여성', 61, '뷰티/의료관광', 0);
INSERT INTO travel_revisit VALUES('여성', 61, '스포츠/레포츠 관람 및 참가 비즈니스 활동', 5);
INSERT INTO travel_revisit VALUES('여성', 61, '업무수행', 4.75);
INSERT INTO travel_revisit VALUES('여성', 61, '연수/교육/연구', 4);
INSERT INTO travel_revisit VALUES('여성', 61, '시찰 (산업시설 등)', 0);
INSERT INTO travel_revisit VALUES('남성', 15, '식도락 관광', 4.46);
INSERT INTO travel_revisit VALUES('남성', 15, '쇼핑', 4.46);
INSERT INTO travel_revisit VALUES('남성', 15, '자연경관 감상', 4.75);
INSERT INTO travel_revisit VALUES('남성', 15, '고궁/역사 유적지 방문', 1);
INSERT INTO travel_revisit VALUES('남성', 15, '전통문화체험', 0);
INSERT INTO travel_revisit VALUES('남성', 15, '박물관, 전시관 관람', 0);
INSERT INTO travel_revisit VALUES('남성', 15, 'K-POP/한류스타 관련 공연장 방문', 0);
INSERT INTO travel_revisit VALUES('남성', 15, '드라마/영화 촬영지 방문', 4);
INSERT INTO travel_revisit VALUES('남성', 15, '연극, 뮤지컬, 발레 등 공연 관람 및 지역 축제 참여', 0);
INSERT INTO travel_revisit VALUES('남성', 15, '지역 축제 참여', 0);
INSERT INTO travel_revisit VALUES('남성', 15, '유흥/오락', 0);
INSERT INTO travel_revisit VALUES('남성', 15, '뷰티/의료관광', 0);
INSERT INTO travel_revisit VALUES('남성', 15, '스포츠/레포츠 관람 및 참가 비즈니스 활동', 0);
INSERT INTO travel_revisit VALUES('남성', 15, '업무수행', 4.71);
INSERT INTO travel_revisit VALUES('남성', 15, '연수/교육/연구', 4.2);
INSERT INTO travel_revisit VALUES('남성', 15, '시찰 (산업시설 등)', 0);
INSERT INTO travel_revisit VALUES('남성', 21, '식도락 관광', 4.34);
INSERT INTO travel_revisit VALUES('남성', 21, '쇼핑', 4.26);
INSERT INTO travel_revisit VALUES('남성', 21, '자연경관 감상', 4.04);
INSERT INTO travel_revisit VALUES('남성', 21, '고궁/역사 유적지 방문', 4.47);
INSERT INTO travel_revisit VALUES('남성', 21, '전통문화체험', 4.75);
INSERT INTO travel_revisit VALUES('남성', 21, '박물관, 전시관 관람', 4.4);
INSERT INTO travel_revisit VALUES('남성', 21, 'K-POP/한류스타 관련 공연장 방문', 0);
INSERT INTO travel_revisit VALUES('남성', 21, '드라마/영화 촬영지 방문', 0);
INSERT INTO travel_revisit VALUES('남성', 21, '연극, 뮤지컬, 발레 등 공연 관람 및 지역 축제 참여', 0);
INSERT INTO travel_revisit VALUES('남성', 21, '지역 축제 참여', 0);
INSERT INTO travel_revisit VALUES('남성', 21, '유흥/오락', 3.67);
INSERT INTO travel_revisit VALUES('남성', 21, '뷰티/의료관광', 4.75);
INSERT INTO travel_revisit VALUES('남성', 21, '스포츠/레포츠 관람 및 참가 비즈니스 활동', 4);
INSERT INTO travel_revisit VALUES('남성', 21, '업무수행', 4.41);
INSERT INTO travel_revisit VALUES('남성', 21, '연수/교육/연구', 4.21);
INSERT INTO travel_revisit VALUES('남성', 21, '시찰 (산업시설 등)', 1.5);
INSERT INTO travel_revisit VALUES('남성', 31, '식도락 관광', 4.33);
INSERT INTO travel_revisit VALUES('남성', 31, '쇼핑', 4.37);
INSERT INTO travel_revisit VALUES('남성', 31, '자연경관 감상', 4.38);
INSERT INTO travel_revisit VALUES('남성', 31, '고궁/역사 유적지 방문', 4.06);
INSERT INTO travel_revisit VALUES('남성', 31, '전통문화체험', 4);
INSERT INTO travel_revisit VALUES('남성', 31, '박물관, 전시관 관람', 3.67);
INSERT INTO travel_revisit VALUES('남성', 31, 'K-POP/한류스타 관련 공연장 방문', 0);
INSERT INTO travel_revisit VALUES('남성', 31, '드라마/영화 촬영지 방문', 4);
INSERT INTO travel_revisit VALUES('남성', 31, '연극, 뮤지컬, 발레 등 공연 관람 및 지역 축제 참여', 0);
INSERT INTO travel_revisit VALUES('남성', 31, '지역 축제 참여', 0);
INSERT INTO travel_revisit VALUES('남성', 31, '유흥/오락', 4);
INSERT INTO travel_revisit VALUES('남성', 31, '뷰티/의료관광', 0);
INSERT INTO travel_revisit VALUES('남성', 31, '스포츠/레포츠 관람 및 참가 비즈니스 활동', 5);
INSERT INTO travel_revisit VALUES('남성', 31, '업무수행', 4.47);
INSERT INTO travel_revisit VALUES('남성', 31, '연수/교육/연구', 4.38);
INSERT INTO travel_revisit VALUES('남성', 31, '시찰 (산업시설 등)', 5);
INSERT INTO travel_revisit VALUES('남성', 41, '식도락 관광', 4.47);
INSERT INTO travel_revisit VALUES('남성', 41, '쇼핑', 4.48);
INSERT INTO travel_revisit VALUES('남성', 41, '자연경관 감상', 4.28);
INSERT INTO travel_revisit VALUES('남성', 41, '고궁/역사 유적지 방문', 4.5);
INSERT INTO travel_revisit VALUES('남성', 41, '전통문화체험', 4);
INSERT INTO travel_revisit VALUES('남성', 41, '박물관, 전시관 관람', 4);
INSERT INTO travel_revisit VALUES('남성', 41, 'K-POP/한류스타 관련 공연장 방문', 0);
INSERT INTO travel_revisit VALUES('남성', 41, '드라마/영화 촬영지 방문', 4);
INSERT INTO travel_revisit VALUES('남성', 41, '연극, 뮤지컬, 발레 등 공연 관람 및 지역 축제 참여', 0);
INSERT INTO travel_revisit VALUES('남성', 41, '지역 축제 참여', 0);
INSERT INTO travel_revisit VALUES('남성', 41, '유흥/오락', 0);
INSERT INTO travel_revisit VALUES('남성', 41, '뷰티/의료관광', 4.5);
INSERT INTO travel_revisit VALUES('남성', 41, '스포츠/레포츠 관람 및 참가 비즈니스 활동', 5);
INSERT INTO travel_revisit VALUES('남성', 41, '업무수행', 4.4);
INSERT INTO travel_revisit VALUES('남성', 41, '연수/교육/연구', 4.27);
INSERT INTO travel_revisit VALUES('남성', 41, '시찰 (산업시설 등)', 5);
INSERT INTO travel_revisit VALUES('남성', 51, '식도락 관광', 4.51);
INSERT INTO travel_revisit VALUES('남성', 51, '쇼핑', 4.51);
INSERT INTO travel_revisit VALUES('남성', 51, '자연경관 감상', 4.43);
INSERT INTO travel_revisit VALUES('남성', 51, '고궁/역사 유적지 방문', 4.67);
INSERT INTO travel_revisit VALUES('남성', 51, '전통문화체험', 5);
INSERT INTO travel_revisit VALUES('남성', 51, '박물관, 전시관 관람', 4);
INSERT INTO travel_revisit VALUES('남성', 51, 'K-POP/한류스타 관련 공연장 방문', 0);
INSERT INTO travel_revisit VALUES('남성', 51, '드라마/영화 촬영지 방문', 0);
INSERT INTO travel_revisit VALUES('남성', 51, '연극, 뮤지컬, 발레 등 공연 관람 및 지역 축제 참여', 0);
INSERT INTO travel_revisit VALUES('남성', 51, '지역 축제 참여', 0);
INSERT INTO travel_revisit VALUES('남성', 51, '유흥/오락', 5);
INSERT INTO travel_revisit VALUES('남성', 51, '뷰티/의료관광', 5);
INSERT INTO travel_revisit VALUES('남성', 51, '스포츠/레포츠 관람 및 참가 비즈니스 활동', 5);
INSERT INTO travel_revisit VALUES('남성', 51, '업무수행', 4.54);
INSERT INTO travel_revisit VALUES('남성', 51, '연수/교육/연구', 4);
INSERT INTO travel_revisit VALUES('남성', 51, '시찰 (산업시설 등)', 0);
INSERT INTO travel_revisit VALUES('남성', 61, '식도락 관광', 4.58);
INSERT INTO travel_revisit VALUES('남성', 61, '쇼핑', 4.69);
INSERT INTO travel_revisit VALUES('남성', 61, '자연경관 감상', 4.4);
INSERT INTO travel_revisit VALUES('남성', 61, '고궁/역사 유적지 방문', 0);
INSERT INTO travel_revisit VALUES('남성', 61, '전통문화체험', 0);
INSERT INTO travel_revisit VALUES('남성', 61, '박물관, 전시관 관람', 0);
INSERT INTO travel_revisit VALUES('남성', 61, 'K-POP/한류스타 관련 공연장 방문', 0);
INSERT INTO travel_revisit VALUES('남성', 61, '드라마/영화 촬영지 방문', 0);
INSERT INTO travel_revisit VALUES('남성', 61, '연극, 뮤지컬, 발레 등 공연 관람 및 지역 축제 참여', 0);
INSERT INTO travel_revisit VALUES('남성', 61, '지역 축제 참여', 0);
INSERT INTO travel_revisit VALUES('남성', 61, '유흥/오락', 0);
INSERT INTO travel_revisit VALUES('남성', 61, '뷰티/의료관광', 0);
INSERT INTO travel_revisit VALUES('남성', 61, '스포츠/레포츠 관람 및 참가 비즈니스 활동', 0);
INSERT INTO travel_revisit VALUES('남성', 61, '업무수행', 4.59);
INSERT INTO travel_revisit VALUES('남성', 61, '연수/교육/연구', 0);
INSERT INTO travel_revisit VALUES('남성', 61, '시찰 (산업시설 등)', 0);


INSERT INTO travel_like VALUES('여성', 15, '서울', 4.73,428);
INSERT INTO travel_like VALUES('여성', 15, '경기도', 4.72,83);
INSERT INTO travel_like VALUES('여성', 15, '인천', 4.76,114);
INSERT INTO travel_like VALUES('여성', 15, '강원도', 4.81,31);
INSERT INTO travel_like VALUES('여성', 15, '충청도', 4.67,48);
INSERT INTO travel_like VALUES('여성', 15, '경상도', 4.77,183);
INSERT INTO travel_like VALUES('여성', 15, '전라도', 4.81,48);
INSERT INTO travel_like VALUES('여성', 15, '제주', 4.8,93);
INSERT INTO travel_like VALUES('여성', 21, '서울', 4.68,1823);
INSERT INTO travel_like VALUES('여성', 21, '경기도', 4.66,462);
INSERT INTO travel_like VALUES('여성', 21, '인천', 4.7,524);
INSERT INTO travel_like VALUES('여성', 21, '강원도', 4.8,259);
INSERT INTO travel_like VALUES('여성', 21, '충청도', 4.63,291);
INSERT INTO travel_like VALUES('여성', 21, '경상도', 4.74,967);
INSERT INTO travel_like VALUES('여성', 21, '전라도', 4.68,360);
INSERT INTO travel_like VALUES('여성', 21, '제주', 4.74,547);
INSERT INTO travel_like VALUES('여성', 31, '서울', 4.64,357);
INSERT INTO travel_like VALUES('여성', 31, '경기도', 4.66,130);
INSERT INTO travel_like VALUES('여성', 31, '인천', 4.71,69);
INSERT INTO travel_like VALUES('여성', 31, '강원도', 4.82,49);
INSERT INTO travel_like VALUES('여성', 31, '충청도', 4.57,49);
INSERT INTO travel_like VALUES('여성', 31, '경상도', 4.61,144);
INSERT INTO travel_like VALUES('여성', 31, '전라도', 4.65,63);
INSERT INTO travel_like VALUES('여성', 31, '제주', 4.72,65);
INSERT INTO travel_like VALUES('여성', 41, '서울', 4.62,143);
INSERT INTO travel_like VALUES('여성', 41, '경기도', 4.6,60);
INSERT INTO travel_like VALUES('여성', 41, '인천', 4.74,23);
INSERT INTO travel_like VALUES('여성', 41, '강원도', 4.81,16);
INSERT INTO travel_like VALUES('여성', 41, '충청도', 4.67,15);
INSERT INTO travel_like VALUES('여성', 41, '경상도', 4.57,60);
INSERT INTO travel_like VALUES('여성', 41, '전라도', 4.84,19);
INSERT INTO travel_like VALUES('여성', 41, '제주', 4.79,19);
INSERT INTO travel_like VALUES('여성', 51, '서울', 4.61,109);
INSERT INTO travel_like VALUES('여성', 51, '경기도', 4.59,44);
INSERT INTO travel_like VALUES('여성', 51, '인천', 4.65,17);
INSERT INTO travel_like VALUES('여성', 51, '강원도', 4.81,16);
INSERT INTO travel_like VALUES('여성', 51, '충청도', 4.61,18);
INSERT INTO travel_like VALUES('여성', 51, '경상도', 4.53,47);
INSERT INTO travel_like VALUES('여성', 51, '전라도', 4.84,19);
INSERT INTO travel_like VALUES('여성', 51, '제주', 4.67,18);
INSERT INTO travel_like VALUES('여성', 61, '서울', 4.64,39);
INSERT INTO travel_like VALUES('여성', 61, '경기도', 4.57,23);
INSERT INTO travel_like VALUES('여성', 61, '인천', 4.78,9);
INSERT INTO travel_like VALUES('여성', 61, '강원도', 4.8,5);
INSERT INTO travel_like VALUES('여성', 61, '충청도', 4.56,9);
INSERT INTO travel_like VALUES('여성', 61, '경상도', 4.56,16);
INSERT INTO travel_like VALUES('여성', 61, '전라도', 4.5,6);
INSERT INTO travel_like VALUES('여성', 61, '제주', 4.75,8);
INSERT INTO travel_like VALUES('남성', 15, '서울', 4.68,138);
INSERT INTO travel_like VALUES('남성', 15, '경기도', 4.73,30);
INSERT INTO travel_like VALUES('남성', 15, '인천', 4.73,52);
INSERT INTO travel_like VALUES('남성', 15, '강원도', 4.86,21);
INSERT INTO travel_like VALUES('남성', 15, '충청도', 4.63,24);
INSERT INTO travel_like VALUES('남성', 15, '경상도', 4.69,59);
INSERT INTO travel_like VALUES('남성', 15, '전라도', 4.71,34);
INSERT INTO travel_like VALUES('남성', 15, '제주', 4.75,32);
INSERT INTO travel_like VALUES('남성', 21, '서울', 4.64,964);
INSERT INTO travel_like VALUES('남성', 21, '경기도', 4.61,357);
INSERT INTO travel_like VALUES('남성', 21, '인천', 4.7,298);
INSERT INTO travel_like VALUES('남성', 21, '강원도', 4.75,114);
INSERT INTO travel_like VALUES('남성', 21, '충청도', 4.47,258);
INSERT INTO travel_like VALUES('남성', 21, '경상도', 4.62,535);
INSERT INTO travel_like VALUES('남성', 21, '전라도', 4.62,218);
INSERT INTO travel_like VALUES('남성', 21, '제주', 4.73,237);
INSERT INTO travel_like VALUES('남성', 31, '서울', 4.52,650);
INSERT INTO travel_like VALUES('남성', 31, '경기도', 4.42,322);
INSERT INTO travel_like VALUES('남성', 31, '인천', 4.5,183);
INSERT INTO travel_like VALUES('남성', 31, '강원도', 4.67,67);
INSERT INTO travel_like VALUES('남성', 31, '충청도', 4.36,196);
INSERT INTO travel_like VALUES('남성', 31, '경상도', 4.54,413);
INSERT INTO travel_like VALUES('남성', 31, '전라도', 4.55,108);
INSERT INTO travel_like VALUES('남성', 31, '제주', 4.68,62);
INSERT INTO travel_like VALUES('남성', 41, '서울', 4.56,387);
INSERT INTO travel_like VALUES('남성', 41, '경기도', 4.44,186);
INSERT INTO travel_like VALUES('남성', 41, '인천', 4.39,83);
INSERT INTO travel_like VALUES('남성', 41, '강원도', 4.64,44);
INSERT INTO travel_like VALUES('남성', 41, '충청도', 4.3,135);
INSERT INTO travel_like VALUES('남성', 41, '경상도', 4.47,230);
INSERT INTO travel_like VALUES('남성', 41, '전라도', 4.38,64);
INSERT INTO travel_like VALUES('남성', 41, '제주', 4.69,29);
INSERT INTO travel_like VALUES('남성', 51, '서울', 4.62,266);
INSERT INTO travel_like VALUES('남성', 51, '경기도', 4.38,128);
INSERT INTO travel_like VALUES('남성', 51, '인천', 4.48,60);
INSERT INTO travel_like VALUES('남성', 51, '강원도', 4.42,33);
INSERT INTO travel_like VALUES('남성', 51, '충청도', 4.42,62);
INSERT INTO travel_like VALUES('남성', 51, '경상도', 4.48,173);
INSERT INTO travel_like VALUES('남성', 51, '전라도', 4.63,27);
INSERT INTO travel_like VALUES('남성', 51, '제주', 4.5,24);
INSERT INTO travel_like VALUES('남성', 61, '서울', 4.63,88);
INSERT INTO travel_like VALUES('남성', 61, '경기도', 4.58,38);
INSERT INTO travel_like VALUES('남성', 61, '인천', 4.71,14);
INSERT INTO travel_like VALUES('남성', 61, '강원도', 4.27,11);
INSERT INTO travel_like VALUES('남성', 61, '충청도', 4.31,13);
INSERT INTO travel_like VALUES('남성', 61, '경상도', 4.57,60);
INSERT INTO travel_like VALUES('남성', 61, '전라도', 4.36,14);
INSERT INTO travel_like VALUES('남성', 61, '제주', 4.6,5);